// Ingredient database with proper measurement units (no nutrition tracking)
export const INGREDIENT_DATABASE: Record<string, any> = {
  // Proteins
  'chicken_breast': { name: 'Chicken Breast', defaultAmount: 4, unit: 'oz', measureType: 'weight' },
  'chicken_thigh': { name: 'Chicken Thigh', defaultAmount: 1, unit: 'piece', measureType: 'count' },
  'beef_steak': { name: 'Beef Steak', defaultAmount: 6, unit: 'oz', measureType: 'weight' },
  'ground_beef': { name: 'Ground Beef', defaultAmount: 4, unit: 'oz', measureType: 'weight' },
  'pork_chop': { name: 'Pork Chop', defaultAmount: 1, unit: 'piece', measureType: 'count' },
  'bacon': { name: 'Bacon', defaultAmount: 2, unit: 'slices', measureType: 'count' },
  'ham': { name: 'Ham', defaultAmount: 3, unit: 'oz', measureType: 'weight' },
  'turkey_breast': { name: 'Turkey Breast', defaultAmount: 3, unit: 'oz', measureType: 'weight' },
  'salmon': { name: 'Salmon', defaultAmount: 4, unit: 'oz', measureType: 'weight' },
  'tuna': { name: 'Tuna', defaultAmount: 1, unit: 'can', measureType: 'count' },
  'shrimp': { name: 'Shrimp', defaultAmount: 6, unit: 'pieces', measureType: 'count' },
  'cod': { name: 'Cod', defaultAmount: 4, unit: 'oz', measureType: 'weight' },
  'eggs': { name: 'Eggs', defaultAmount: 2, unit: 'eggs', measureType: 'count' },
  'tofu': { name: 'Tofu', defaultAmount: 4, unit: 'oz', measureType: 'weight' },
  'tempeh': { name: 'Tempeh', defaultAmount: 3, unit: 'oz', measureType: 'weight' },
  'black_beans': { name: 'Black Beans', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'chickpeas': { name: 'Chickpeas', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'lentils': { name: 'Lentils', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'kidney_beans': { name: 'Kidney Beans', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'pinto_beans': { name: 'Pinto Beans', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  
  // Vegetables
  'tomato': { name: 'Tomato', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'lettuce': { name: 'Lettuce', defaultAmount: 2, unit: 'cups', measureType: 'volume' },
  'spinach': { name: 'Spinach', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'kale': { name: 'Kale', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'arugula': { name: 'Arugula', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'onion': { name: 'Onion', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'garlic': { name: 'Garlic', defaultAmount: 2, unit: 'cloves', measureType: 'count' },
  'carrot': { name: 'Carrot', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'celery': { name: 'Celery', defaultAmount: 2, unit: 'stalks', measureType: 'count' },
  'bell_pepper': { name: 'Bell Pepper', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'broccoli': { name: 'Broccoli', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'cauliflower': { name: 'Cauliflower', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'brussels_sprouts': { name: 'Brussels Sprouts', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'cabbage': { name: 'Cabbage', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'zucchini': { name: 'Zucchini', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'cucumber': { name: 'Cucumber', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'eggplant': { name: 'Eggplant', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'mushroom': { name: 'Mushroom', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'asparagus': { name: 'Asparagus', defaultAmount: 6, unit: 'spears', measureType: 'count' },
  'green_beans': { name: 'Green Beans', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'peas': { name: 'Peas', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'corn': { name: 'Corn', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'potato': { name: 'Potato', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'sweet_potato': { name: 'Sweet Potato', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  
  // Fruits
  'apple': { name: 'Apple', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'banana': { name: 'Banana', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'orange': { name: 'Orange', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'strawberry': { name: 'Strawberry', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'blueberry': { name: 'Blueberry', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'raspberry': { name: 'Raspberry', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'blackberry': { name: 'Blackberry', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'grape': { name: 'Grape', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'watermelon': { name: 'Watermelon', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'cantaloupe': { name: 'Cantaloupe', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'pineapple': { name: 'Pineapple', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'mango': { name: 'Mango', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'peach': { name: 'Peach', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'pear': { name: 'Pear', defaultAmount: 1, unit: 'medium', measureType: 'count' },
  'avocado': { name: 'Avocado', defaultAmount: 1, unit: 'whole', measureType: 'count' },
  
  // Grains & Starches
  'white_rice': { name: 'White Rice', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'brown_rice': { name: 'Brown Rice', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'quinoa': { name: 'Quinoa', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'oats': { name: 'Oats', defaultAmount: 0.5, unit: 'cup', measureType: 'volume' },
  'pasta': { name: 'Pasta', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'bread': { name: 'Bread', defaultAmount: 2, unit: 'slices', measureType: 'count' },
  'tortilla': { name: 'Tortilla', defaultAmount: 1, unit: 'piece', measureType: 'count' },
  'naan': { name: 'Naan', defaultAmount: 1, unit: 'piece', measureType: 'count' },
  
  // Dairy & Alternatives
  'milk': { name: 'Milk', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'cheese': { name: 'Cheese', defaultAmount: 1, unit: 'oz', measureType: 'weight' },
  'yogurt': { name: 'Yogurt', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'butter': { name: 'Butter', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'cream': { name: 'Cream', defaultAmount: 2, unit: 'tbsp', measureType: 'volume' },
  'sour_cream': { name: 'Sour Cream', defaultAmount: 2, unit: 'tbsp', measureType: 'volume' },
  'cottage_cheese': { name: 'Cottage Cheese', defaultAmount: 0.5, unit: 'cup', measureType: 'volume' },
  'almond_milk': { name: 'Almond Milk', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'soy_milk': { name: 'Soy Milk', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'oat_milk': { name: 'Oat Milk', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  
  // Nuts & Seeds
  'almonds': { name: 'Almonds', defaultAmount: 0.25, unit: 'cup', measureType: 'volume' },
  'peanuts': { name: 'Peanuts', defaultAmount: 0.25, unit: 'cup', measureType: 'volume' },
  'cashews': { name: 'Cashews', defaultAmount: 0.25, unit: 'cup', measureType: 'volume' },
  'walnuts': { name: 'Walnuts', defaultAmount: 0.25, unit: 'cup', measureType: 'volume' },
  'peanut_butter': { name: 'Peanut Butter', defaultAmount: 2, unit: 'tbsp', measureType: 'volume' },
  'almond_butter': { name: 'Almond Butter', defaultAmount: 2, unit: 'tbsp', measureType: 'volume' },
  
  // Oils & Condiments
  'olive_oil': { name: 'Olive Oil', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'vegetable_oil': { name: 'Vegetable Oil', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'coconut_oil': { name: 'Coconut Oil', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'vinegar': { name: 'Vinegar', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'soy_sauce': { name: 'Soy Sauce', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'ketchup': { name: 'Ketchup', defaultAmount: 2, unit: 'tbsp', measureType: 'volume' },
  'mustard': { name: 'Mustard', defaultAmount: 1, unit: 'tsp', measureType: 'volume' },
  'mayonnaise': { name: 'Mayonnaise', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'honey': { name: 'Honey', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'maple_syrup': { name: 'Maple Syrup', defaultAmount: 2, unit: 'tbsp', measureType: 'volume' },
  
  // Herbs & Spices
  'salt': { name: 'Salt', defaultAmount: 1, unit: 'tsp', measureType: 'volume' },
  'pepper': { name: 'Pepper', defaultAmount: 0.25, unit: 'tsp', measureType: 'volume' },
  'basil': { name: 'Basil', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'oregano': { name: 'Oregano', defaultAmount: 1, unit: 'tsp', measureType: 'volume' },
  'thyme': { name: 'Thyme', defaultAmount: 1, unit: 'tsp', measureType: 'volume' },
  'rosemary': { name: 'Rosemary', defaultAmount: 1, unit: 'tsp', measureType: 'volume' },
  'cilantro': { name: 'Cilantro', defaultAmount: 2, unit: 'tbsp', measureType: 'volume' },
  'parsley': { name: 'Parsley', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  'ginger': { name: 'Ginger', defaultAmount: 1, unit: 'tsp', measureType: 'volume' },
  'cumin': { name: 'Cumin', defaultAmount: 1, unit: 'tsp', measureType: 'volume' },
  'paprika': { name: 'Paprika', defaultAmount: 1, unit: 'tsp', measureType: 'volume' },
  
  // Additional common ingredients
  'wine': { name: 'Wine', defaultAmount: 5, unit: 'oz', measureType: 'volume' },
  'chocolate': { name: 'Chocolate', defaultAmount: 1, unit: 'oz', measureType: 'weight' },
  'nuts': { name: 'Mixed Nuts', defaultAmount: 0.25, unit: 'cup', measureType: 'volume' },
  'flour': { name: 'Flour', defaultAmount: 1, unit: 'cup', measureType: 'volume' },
  'sugar': { name: 'Sugar', defaultAmount: 1, unit: 'tbsp', measureType: 'volume' },
  
  // Default for unknown ingredients
  'default': { name: 'Unknown Food', defaultAmount: 1, unit: 'serving', measureType: 'count' }
};